# Generated by Django 4.2.5 on 2023-10-04 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosConteudoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=1999)),
            ],
        ),
        migrations.CreateModel(
            name='GRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.FloatField(blank=True, default=None, null=True)),
                ('numero', models.CharField(max_length=140)),
                ('ano_mudanca', models.IntegerField(blank=True, default='GRI-', null=True)),
                ('slug', models.SlugField(default='', help_text='Numero do GRI ', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=1999)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('0', 'Iniciado'), ('1', 'Não Iniciado'), ('2', 'A Validar'), ('3', 'Concluido')], max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas', models.CharField(choices=[('capacidade', 'Capacidade'), ('comprimento', 'Comprimento'), ('massa', 'Massa'), ('volume', 'Volume')], max_length=140)),
                ('volumes', models.CharField(choices=[('l', 'Litros'), ('kg', 'Quilogramas'), ('m3', 'Metro Cúbico'), ('m', 'Metros'), ('g', 'Gramas')], max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloGRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decricao', models.TextField()),
                ('tema_material', models.CharField(default='', max_length=200)),
                ('topico_gri', models.CharField(max_length=200)),
                ('relevancia', models.TextField()),
                ('fontes', models.TextField()),
                ('references', models.TextField(default='')),
                ('definicoes', models.TextField()),
                ('gri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.gri')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=140)),
                ('comentario', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('Ambiental', 'Ambiental'), ('Social', 'Social'), ('Economico', 'Economico')], max_length=140)),
                ('ano_criacao', models.IntegerField(default=2023)),
                ('slug', models.SlugField(default='', help_text='Nome do Tema')),
                ('gri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.gri')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.status')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoGRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_numero', models.CharField(max_length=100)),
                ('ano_mudanca', models.IntegerField()),
                ('gri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.gri')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInformacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=150)),
                ('fabrica', models.CharField(max_length=150)),
                ('e_certificada', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')])),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('dados_conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.dadosconteudoindicador')),
            ],
        ),
        migrations.AddField(
            model_name='dadosconteudoindicador',
            name='indicador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ava.indicador'),
        ),
    ]
