# Generated by Django 4.2.5 on 2023-09-26 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('porcentagem', models.FloatField(blank=True, default=None, null=True)),
                ('numero', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('Iniciado', '0'), ('Não Iniciado', '1'), ('A Validar', '2'), ('Concluido', '3')], max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=140)),
                ('medida', models.CharField(max_length=140)),
                ('responsavel', models.CharField(max_length=140)),
                ('comentario', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('Ambiental', 'Ambiental'), ('Social', 'Social'), ('Economico', 'Economico')], max_length=140)),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('id_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.gri')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.status')),
            ],
        ),
    ]
