# Generated by Django 4.2.5 on 2023-10-11 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='indicador',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
