# Generated by Django 4.2.5 on 2023-09-26 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(max_length=100)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.indicador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
