# Generated by Django 4.2.5 on 2023-10-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0003_indicador_validador_alter_indicador_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='validador',
        ),
    ]
