# Generated by Django 4.2.5 on 2023-09-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0003_alter_indicador_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoindicador',
            old_name='usuario',
            new_name='responsavel',
        ),
        migrations.RemoveField(
            model_name='historicoindicador',
            name='status_anterior',
        ),
        migrations.AddField(
            model_name='historicoindicador',
            name='novo_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
