# Generated by Django 4.2.5 on 2023-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_rename_usuario_historicoindicador_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoindicador',
            name='antigo_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='indicador',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
