# Generated by Django 4.2.5 on 2023-10-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0005_remove_indicador_responsavel_indicador_responsaveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='responsaveis',
            new_name='responsavel',
        ),
    ]
