# Generated by Django 4.2.5 on 2023-09-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0005_historicoindicador_antigo_status_indicador_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
