# Generated by Django 4.2.5 on 2023-10-11 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ava', '0006_rename_responsaveis_indicador_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='indicador',
            name='responsaveis',
            field=models.ManyToManyField(related_name='indicadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
