# Generated by Django 4.2.5 on 2023-09-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0006_alter_indicador_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='id_indicador',
            new_name='gri',
        ),
    ]
