# Generated by Django 4.2.5 on 2023-09-27 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0007_rename_id_indicador_indicador_gri'),
    ]

    operations = [
        migrations.AddField(
            model_name='gri',
            name='ano_mudanca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoGRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_numero', models.CharField(max_length=100)),
                ('ano_mudanca', models.IntegerField()),
                ('gri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.gri')),
            ],
        ),
    ]
