# Generated by Django 4.2.5 on 2023-09-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0008_gri_ano_mudanca_historicogri'),
    ]

    operations = [
        migrations.AddField(
            model_name='gri',
            name='slug',
            field=models.SlugField(default='gri.nome', max_length=100, unique=True),
        ),
    ]
