# Generated by Django 4.2.5 on 2023-09-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0009_gri_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas', models.CharField(choices=[('Litros', 'l'), ('Quilograma ', 'kg'), ('Metro Cúbico', 'm3'), ('Metro', '3')], max_length=140)),
                ('volumes', models.CharField(choices=[('Litros', 'l'), ('Quilograma ', 'kg'), ('Metro Cúbico', 'm3'), ('Metro', 'm'), ('Grama', 'g')], max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='gri',
            name='slug',
            field=models.SlugField(default='Numero', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.unidadesmedidas'),
        ),
    ]
