# Generated by Django 4.2.5 on 2023-09-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0010_unidadesmedidas_alter_gri_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesmedidas',
            name='medidas',
            field=models.CharField(choices=[('capacidade', 'Capacidade'), ('comprimento', 'Comprimento'), ('massa', 'Massa'), ('volume', 'Volume')], max_length=140),
        ),
        migrations.AlterField(
            model_name='unidadesmedidas',
            name='volumes',
            field=models.CharField(choices=[('l', 'Litros'), ('kg', 'Quilogramas'), ('m3', 'Metro Cúbico'), ('m', 'Metros'), ('g', 'Gramas')], max_length=140),
        ),
    ]
