# Generated by Django 4.2.5 on 2023-09-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0012_alter_status_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gri',
            name='slug',
            field=models.SlugField(default='', help_text='Numero do GRI ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='slug',
            field=models.SlugField(default='', help_text='Nome do Tema'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.ForeignKey(help_text='0= Iniciado, 1= Não Iniciado, 2= A Validar, 3= Concluido', on_delete=django.db.models.deletion.CASCADE, to='ava.status'),
        ),
    ]
