# Generated by Django 4.2.5 on 2023-09-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0013_alter_gri_slug_alter_indicador_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gri',
            name='nome',
        ),
        migrations.AlterField(
            model_name='gri',
            name='ano_mudanca',
            field=models.IntegerField(blank=True, default='GRI-', null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.status'),
        ),
        migrations.CreateModel(
            name='ConteudoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decricao', models.TextField()),
                ('topico_gri', models.CharField(max_length=200)),
                ('relevancia', models.TextField()),
                ('fontes', models.TextField()),
                ('definicoes', models.TextField()),
                ('tema_material', models.ManyToManyField(to='ava.indicador')),
            ],
        ),
    ]
