# Generated by Django 4.2.5 on 2023-09-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0014_remove_gri_nome_alter_gri_ano_mudanca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='medida',
        ),
    ]
