# Generated by Django 4.2.5 on 2023-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0014_alter_indicador_responsaveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinformacoes',
            name='e_certificada',
            field=models.IntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não')]),
        ),
    ]
