# Generated by Django 4.2.5 on 2023-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0015_alter_grupoinformacoes_e_certificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinformacoes',
            name='e_certificada',
            field=models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
    ]
