# Generated by Django 4.2.5 on 2023-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0016_remove_conteudoindicador_tema_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoindicador',
            name='references',
            field=models.TextField(default=''),
        ),
    ]
