# Generated by Django 4.2.5 on 2023-10-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0018_grupoinformacoes_remove_informacoestabela_coluna1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ava.empresa'),
        ),
        migrations.AlterField(
            model_name='grupoinformacoes',
            name='fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.fabrica'),
        ),
        migrations.AlterField(
            model_name='grupoinformacoes',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.fabricante'),
        ),
    ]
