# Generated by Django 4.2.5 on 2023-10-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0019_fabricante_empresa_alter_grupoinformacoes_fabrica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ava.empresa'),
        ),
    ]
