# Generated by Django 4.2.5 on 2023-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0020_indicador_resposta_alter_fabricante_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosconteudoindicador',
            name='resp_indicador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
