# Generated by Django 4.2.5 on 2023-10-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0022_indicador_quant_colunas_informacoestabela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='informacoes_tabela',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='quant_colunas',
        ),
        migrations.DeleteModel(
            name='InformacoesTabela',
        ),
    ]
