# Generated by Django 4.2.5 on 2023-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0024_indicador_quant_colunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('num_colunas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
