# Generated by Django 4.2.5 on 2023-10-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0025_tabeladinamica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelaDinamica',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='quant_colunas',
        ),
        migrations.AddField(
            model_name='indicador',
            name='dados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
