# Generated by Django 4.2.5 on 2023-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0026_delete_tabeladinamica_remove_indicador_quant_colunas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabrica',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='fabrica',
            name='fabricante',
            field=models.ManyToManyField(related_name='fabricas', to='ava.fabricante'),
        ),
    ]
