# Generated by Django 4.2.5 on 2023-10-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0027_remove_fabrica_fabricante_fabrica_fabricante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabrica',
            old_name='fabricante',
            new_name='fabricantes',
        ),
    ]
