# Generated by Django 4.2.5 on 2023-10-16 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0028_rename_fabricante_fabrica_fabricantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabrica',
            name='fabricantes',
        ),
        migrations.AddField(
            model_name='fabrica',
            name='fabricantes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ava.fabricante'),
        ),
    ]
