# Generated by Django 4.2.5 on 2023-10-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0029_remove_fabrica_fabricantes_fabrica_fabricantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='colunas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
