# Generated by Django 4.2.5 on 2023-10-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0030_indicador_colunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
