# Generated by Django 4.2.5 on 2023-10-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0031_indicador_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(default=1999)),
                ('duracao_semanas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
