# Generated by Django 4.2.5 on 2023-10-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0036_topico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topico',
            old_name='pergunta',
            new_name='info',
        ),
    ]
