# Generated by Django 4.2.5 on 2023-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0038_rename_topico_infohead_remove_indicador_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='duracao_semanas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateTimeField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
