# Generated by Django 4.2.7 on 2023-11-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0040_alter_tarefa_data_fim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='formulario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ava.formulario'),
        ),
    ]
