# Generated by Django 4.2.7 on 2023-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0041_formulario_indicador_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='possui_fabricante',
            field=models.CharField(choices=[('0', 'Sim'), ('1', 'Nao')], default='', max_length=140),
        ),
    ]
