# Generated by Django 4.2.7 on 2023-11-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0042_formulario_possui_fabricante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoinformacoes',
            name='fabrica',
        ),
        migrations.RemoveField(
            model_name='grupoinformacoes',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='formulario',
            name='fabrica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ava.fabrica'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='fabricante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ava.fabricante'),
        ),
    ]
