# Generated by Django 4.2.7 on 2023-11-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0044_formulario_nome_coluna_alter_formulario_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fabrica',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ava.fabrica'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='fabricante',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ava.fabricante'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nome_coluna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='possui_fabricante',
            field=models.CharField(choices=[('0', 'Sim'), ('1', 'Nao')], default='', max_length=1),
        ),
    ]
