# Generated by Django 4.2.7 on 2023-11-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0045_alter_formulario_fabrica_alter_formulario_fabricante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='nome_coluna',
            new_name='coluna_fixa',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='colunas',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='dados',
        ),
    ]
