# Generated by Django 4.2.7 on 2023-11-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0046_rename_nome_coluna_formulario_coluna_fixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='colunas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
