# Generated by Django 4.2.7 on 2023-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0047_formulario_colunas_formulario_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nome_formulario',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
