# Generated by Django 4.2.7 on 2023-11-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0048_formulario_nome_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaConteudoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_fabricante', models.CharField(choices=[('0', 'Sim'), ('1', 'Nao')], default='', max_length=1)),
                ('ano_criacao', models.IntegerField(default=2023)),
                ('coluna_fixa', models.CharField(blank=True, max_length=255, null=True)),
                ('colunas', models.JSONField(blank=True, null=True)),
                ('dados', models.JSONField(blank=True, null=True)),
                ('fabrica', models.ManyToManyField(blank=True, default='', to='ava.fabrica')),
                ('fabricante', models.ManyToManyField(blank=True, default='', to='ava.fabricante')),
            ],
        ),
        migrations.RemoveField(
            model_name='dadosconteudoindicador',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='descricaocolunaform',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='grupoinformacoes',
            name='dados_conteudo',
        ),
        migrations.RemoveField(
            model_name='historicogri',
            name='gri',
        ),
        migrations.DeleteModel(
            name='HistoricoIndicador',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='coluna_fixa',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='colunas',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='dados',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='fabrica',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='possui_fabricante',
        ),
        migrations.RemoveField(
            model_name='gri',
            name='ano_mudanca',
        ),
        migrations.RemoveField(
            model_name='gri',
            name='porcentagem',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='ano_criacao',
        ),
        migrations.DeleteModel(
            name='DadosConteudoIndicador',
        ),
        migrations.DeleteModel(
            name='DescricaoColunaForm',
        ),
        migrations.DeleteModel(
            name='GrupoInformacoes',
        ),
        migrations.DeleteModel(
            name='HistoricoGRI',
        ),
        migrations.AddField(
            model_name='descricaotabela',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.tabelaconteudoindicador'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tabela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ava.tabelaconteudoindicador'),
        ),
    ]
