# Generated by Django 4.2.7 on 2023-11-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0049_descricaotabela_tabelaconteudoindicador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaconteudoindicador',
            name='fabrica',
        ),
        migrations.RemoveField(
            model_name='tabelaconteudoindicador',
            name='fabricante',
        ),
    ]
