# Generated by Django 4.2.7 on 2023-11-24 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ava', '0050_remove_tabelaconteudoindicador_fabrica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='responsaveis',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='validadores',
        ),
        migrations.AddField(
            model_name='formulario',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='responsaveis_indicadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulario',
            name='validadores',
            field=models.ManyToManyField(blank=True, related_name='validadores_indicadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
