# Generated by Django 4.2.7 on 2023-11-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0053_alter_formulario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='status',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='ava.status'),
        ),
    ]
