# Generated by Django 4.2.7 on 2023-11-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0054_alter_formulario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='perguntas',
            name='indicador',
        ),
        migrations.AddField(
            model_name='perguntas',
            name='tabela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ava.tabelaconteudoindicador'),
        ),
        migrations.AddField(
            model_name='tabelaconteudoindicador',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
