# Generated by Django 4.2.7 on 2023-11-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0055_remove_indicador_resposta_remove_perguntas_indicador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicioesProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicao', models.TextField(default='Definição de ')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decricao', models.TextField()),
                ('tema_material', models.CharField(default='', max_length=200)),
                ('topico_gri', models.CharField(max_length=200)),
                ('relevancia', models.TextField()),
                ('fontes', models.TextField()),
                ('referencias', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='comentario',
        ),
        migrations.AddField(
            model_name='formulario',
            name='comentario',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.DeleteModel(
            name='ProtocoloGRI',
        ),
        migrations.AddField(
            model_name='protocoloindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.indicador'),
        ),
        migrations.AddField(
            model_name='definicioesprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.protocoloindicador'),
        ),
    ]
