# Generated by Django 4.2.7 on 2023-11-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0057_remove_infohead_indicador_infohead_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicioesprotocolo',
            name='titulo',
            field=models.TextField(default='Definição de '),
        ),
        migrations.AlterField(
            model_name='definicioesprotocolo',
            name='definicao',
            field=models.TextField(),
        ),
    ]
