# Generated by Django 4.2.7 on 2023-11-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0058_definicioesprotocolo_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoloindicador',
            name='formulario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ava.formulario'),
        ),
    ]
