# Generated by Django 4.2.7 on 2023-11-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0059_protocoloindicador_formulario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefinicioesProtocolo',
            new_name='DefinicoesProtocolo',
        ),
    ]
