# Generated by Django 4.2.7 on 2023-11-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0060_rename_definicioesprotocolo_definicoesprotocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='tabela',
        ),
        migrations.AddField(
            model_name='tabelaconteudoindicador',
            name='formulario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ava.formulario'),
        ),
    ]
