# Generated by Django 4.2.7 on 2023-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0062_rename_decricao_protocoloindicador_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='indicador',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
    ]
