# Generated by Django 4.2.7 on 2023-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0063_formulario_ano_indicador_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='valor',
            field=models.CharField(choices=[('0', 'Em Andamento'), ('1', 'Não Iniciado'), ('2', 'A Validar'), ('3', 'Concluido')], max_length=140),
        ),
    ]
