# Generated by Django 4.2.7 on 2023-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0065_remove_tabelaconteudoindicador_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='resposta',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
