# Generated by Django 4.2.7 on 2023-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0066_perguntas_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='valor',
            field=models.CharField(choices=[('0', 'Em Andamento'), ('1', 'Não Iniciado'), ('2', 'A Validar'), ('3', 'Concluido'), ('4', 'Em Atraso')], max_length=140),
        ),
    ]
